[tool.poetry]
name = "drebedengi-python-api"
version = "0.2.0"
homepage = "https://github.com/mishamsk/drebedengi-python-api"
description = "Python wrapper for Drebedengi SOAP API."
authors = ["Mike Perlov <mishamsk@gmail.com>"]
readme = "README.md"
license = "GPL-3.0-only"
classifiers = [
    'Development Status :: 2 - Pre-Alpha',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
    'Natural Language :: English',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
]
packages = [{ include = "drebedengi", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.10, <=3.11"
click = "^8.1.3"
zeep = "^4.2.0"
attrs = "^22.1.0"

[tool.poetry.group.dev.dependencies]
tox = "^3.27.0"
twine = "^4.0.1"
black = "^22.10.0"
flake8 = "^5.0.4"
isort = "^5.10.1"
bump2version = "^1.0.1"
pre-commit = "^2.20.0"
tox-gh-actions = "^2.10.0"

[tool.poetry.group.test.dependencies]
pytest = "^7.2.0"
pytest-cov = "^4.0.0"

[tool.poetry.group.mypy.dependencies]
mypy = "^0.982"
types-requests = "^2.28.8"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.4.2"
mkdocs-include-markdown-plugin = "^3.9.1"
mkdocs-material-extensions = "^1.1"
mkdocs-material = "^8.5.10"
mkdocs-section-index = "^0.3.4"
mkdocs-literate-nav = "^0.5.0"
mkdocs-gen-files = "^0.4.0"
mkdocs-exclude = "^1.0.2"
mkdocs-autorefs = "^0.4.1"
mkdocstrings = {version = "^0.19.0", extras = ["python"]}


[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--basetemp=testtemp"

[tool.coverage.run]
omit = ["*/test/*", "**/conftest.py"]

[tool.coverage.report]
omit = ["*/test/*"]
exclude_lines = [
    "pragma: no cover",
    "@abstractmethod",
    "@abc.abstractmethod",
    "def __repr__",
    "if .*DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
]

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100
skip_gitignore = true
known_typing = "typing"
sections = [
    "FUTURE",
    "STDLIB",
    "FIRSTPARTY",
    "THIRDPARTY",
    "LOCALFOLDER",
    "TYPING",
]
# skip files
#skip_glob = docs/conf.py
[tool.mypy]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"
