name: test workflow

on:
  # Triggers the workflow on push & pull request events for any branch
  - push
  - pull_request

  # Allows you to run this workflow manually from the Actions tab
  - workflow_dispatch

permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    strategy:
      matrix:
        python-versions: ["3.10", "3.11"]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    env:
      FORCE_COLOR: "1"
      PRE_COMMIT_COLOR: "always"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry==1.2.1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-versions }}
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry install

      - name: test with tox
        run: poetry run tox
